version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vite-plugin-windicss
    versions:
    - 0.13.1
    - 0.14.0
    - 0.14.6
    - 0.15.2
  - dependency-name: chalk
    versions:
    - 4.1.1
  - dependency-name: ws
    versions:
    - 7.4.5
  - dependency-name: vite
    versions:
    - 2.2.1
  - dependency-name: pg
    versions:
    - 8.6.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.3
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.2
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: node-notifier
    versions:
    - 8.0.1
    - 8.0.2
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: "@types/koa"
    versions:
    - 2.11.7
    - 2.11.8
    - 2.13.0
    - 2.13.1
  - dependency-name: less-loader
    versions:
    - 7.3.0
  - dependency-name: socket.io
    versions:
    - 3.1.0
  - dependency-name: webpack
    versions:
    - 4.46.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: file-loader
    versions:
    - 6.2.0
  - dependency-name: eslint-plugin-react-hooks
    versions:
    - 4.2.0
  - dependency-name: eslint-plugin-import
    versions:
    - 2.22.1
  - dependency-name: bowser
    versions:
    - 2.11.0
  - dependency-name: react-hot-loader
    versions:
    - 4.13.0
