name: Build and Deploy
on:
  push:
    # branches:
    #   - dev
    tags:
      - v*
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy
        run: |
          npm i -g yarn
          yarn
          yarn run build
        env:
          CI: true
